// Datos iniciales de los chats con fechas reales para agrupamiento por d├¡a
const now = new Date();
const t = (h, m) => { const d = new Date(now); d.setHours(h, m, 0, 0); return d.toISOString(); };
const daysAgo = (n, h = 10, m = 0) => { const d = new Date(now); d.setDate(d.getDate() - n); d.setHours(h, m, 0, 0); return d.toISOString(); };

export const initialChats = [
  {
    id: '1',
    name: 'Matias Gimenez (Profesor)',
    avatar: 'https://ui-avatars.com/api/?name=Matias+Gimenez&background=0D8ABC&color=fff',
    lastMessage: 'Entendido profe. Ma├▒ana lo entregamos.',
    timestamp: t(10, 31),
    unread: 1,
    isFavorite: true,
    messages: [
      { id: 'm1a', sender: 'Matias Gimenez', text: 'Chicos, ┬┐c├│mo vienen con el proyecto?', timestamp: daysAgo(3, 9, 0), isMe: false, status: 'read' },
      { id: 'm1b', sender: 'Me', text: 'Todo bien profe, ultimando detalles ≡ƒÆ╗', timestamp: daysAgo(3, 9, 15), isMe: true, status: 'read' },
      { id: 'm1c', sender: 'Matias Gimenez', text: 'Bien. Recuerden que cuenta el 40% de la nota.', timestamp: daysAgo(3, 9, 20), isMe: false, status: 'read' },
      { id: 'm1d', sender: 'Me', text: '┬┐Hay alg├║n punto espec├¡fico que revisar?', timestamp: daysAgo(2, 18, 0), isMe: true, status: 'read' },
      { id: 'm1e', sender: 'Matias Gimenez', text: 'S├¡, la parte de la base de datos. Revisen las relaciones.', timestamp: daysAgo(2, 18, 30), isMe: false, status: 'read' },
      { id: 'm1f', sender: 'Me', text: 'Listo, lo corregimos.', timestamp: daysAgo(1, 20, 0), isMe: true, status: 'read' },
      { id: 'm1g', sender: 'Matias Gimenez', text: 'No se olviden de entregar el TP final ma├▒ana.', timestamp: t(10, 28), isMe: false, status: 'read' },
      { id: 'm1h', sender: 'Me', text: 'Entendido profe. Ma├▒ana lo entregamos.', timestamp: t(10, 31), isMe: true, status: 'sent' },
    ],
  },
  {
    id: '2',
    name: 'Jacobo Winograd',
    avatar: 'https://ui-avatars.com/api/?name=Jacobo+Winograd&background=2ecc71&color=fff',
    lastMessage: '┬íBilletera mata gal├ín!',
    timestamp: daysAgo(1, 14, 22),
    unread: 0,
    messages: [
      { id: 'm2a', sender: 'Jacobo Winograd', text: '┬┐Vas a ir al asado del s├íbado?', timestamp: daysAgo(4, 11, 0), isMe: false, status: 'read' },
      { id: 'm2b', sender: 'Me', text: 'Si, ah├¡ voy a estar ≡ƒöÑ', timestamp: daysAgo(4, 11, 5), isMe: true, status: 'read' },
      { id: 'm2c', sender: 'Jacobo Winograd', text: '┬íNo son mis hijos!', timestamp: daysAgo(2, 20, 10), isMe: false, status: 'read' },
      { id: 'm2d', sender: 'Me', text: 'Tranquilo Jacobo.', timestamp: daysAgo(2, 20, 12), isMe: true, status: 'read' },
      { id: 'm2e', sender: 'Me', text: '┬┐Todo bien?', timestamp: daysAgo(1, 14, 20), isMe: true, status: 'read' },
      { id: 'm2f', sender: 'Jacobo Winograd', text: '┬íBilletera mata gal├ín!', timestamp: daysAgo(1, 14, 22), isMe: false, status: 'read' },
    ],
  },
  {
    id: '4',
    name: 'David Coverdale',
    avatar: 'https://ui-avatars.com/api/?name=David+Coverdale&background=e67e22&color=fff',
    lastMessage: 'Still of the night! ≡ƒÄ╕',
    timestamp: daysAgo(2, 23, 55),
    unread: 0,
    messages: [
      { id: 'm4a', sender: 'David Coverdale', text: '┬┐Escuchaste el ├║ltimo ├ílbum?', timestamp: daysAgo(6, 15, 0), isMe: false, status: 'read' },
      { id: 'm4b', sender: 'Me', text: 'S├¡, es una obra maestra.', timestamp: daysAgo(6, 15, 10), isMe: true, status: 'read' },
      { id: 'm4c', sender: 'David Coverdale', text: 'Are you ready to rock? ≡ƒñÿ', timestamp: daysAgo(2, 23, 50), isMe: false, status: 'read' },
      { id: 'm4d', sender: 'Me', text: 'Always!', timestamp: daysAgo(2, 23, 52), isMe: true, status: 'read' },
      { id: 'm4e', sender: 'David Coverdale', text: 'Still of the night! ≡ƒÄ╕', timestamp: daysAgo(2, 23, 55), isMe: false, status: 'read' },
    ],
  },
  {
    id: '5',
    name: 'Damon Salvatore',
    avatar: 'https://ui-avatars.com/api/?name=Damon+Salvatore&background=2c3e50&color=fff',
    lastMessage: 'Hello, brother.',
    timestamp: daysAgo(3, 3, 0),
    unread: 3,
    isFavorite: true,
    messages: [
      { id: 'm5a', sender: 'Damon Salvatore', text: 'I promised you an eternity of misery.', timestamp: daysAgo(7, 22, 0), isMe: false, status: 'read' },
      { id: 'm5b', sender: 'Me', text: 'Not today, Damon.', timestamp: daysAgo(7, 22, 5), isMe: true, status: 'read' },
      { id: 'm5c', sender: 'Damon Salvatore', text: 'Do you wanna know what I am?', timestamp: daysAgo(5, 1, 0), isMe: false, status: 'read' },
      { id: 'm5d', sender: 'Me', text: 'A vampire, Damon. Siempre lo mismo.', timestamp: daysAgo(5, 1, 10), isMe: true, status: 'read' },
      { id: 'm5e', sender: 'Damon Salvatore', text: 'Rude.', timestamp: daysAgo(5, 1, 12), isMe: false, status: 'read' },
      { id: 'm5f', sender: 'Damon Salvatore', text: 'Hello, brother.', timestamp: daysAgo(3, 3, 0), isMe: false, status: 'read' },
    ],
  },
  {
    id: '6',
    name: 'Klaus Mikaelson',
    avatar: 'https://ui-avatars.com/api/?name=Klaus+Mikaelson&background=8e44ad&color=fff',
    lastMessage: 'I am the hybrid. ≡ƒÉ║',
    timestamp: daysAgo(4, 16, 45),
    unread: 5,
    isFavorite: true,
    messages: [
      { id: 'm6a', sender: 'Klaus Mikaelson', text: 'Family is power.', timestamp: daysAgo(10, 12, 0), isMe: false, status: 'read' },
      { id: 'm6b', sender: 'Me', text: 'Always and forever.', timestamp: daysAgo(10, 12, 5), isMe: true, status: 'read' },
      { id: 'm6c', sender: 'Klaus Mikaelson', text: 'Are you threatening me, love?', timestamp: daysAgo(6, 20, 0), isMe: false, status: 'read' },
      { id: 'm6d', sender: 'Me', text: 'Solo pregunto, Klaus.', timestamp: daysAgo(6, 20, 3), isMe: true, status: 'read' },
      { id: 'm6e', sender: 'Klaus Mikaelson', text: 'I am the hybrid. ≡ƒÉ║', timestamp: daysAgo(4, 16, 45), isMe: false, status: 'read' },
    ],
  },
  {
    id: '8',
    name: 'Stefan Salvatore',
    avatar: 'https://ui-avatars.com/api/?name=Stefan+Salvatore&background=1a252f&color=fff',
    lastMessage: 'I have to protect Elena.',
    timestamp: daysAgo(5, 22, 10),
    unread: 2,
    messages: [
      { id: 'm8a', sender: 'Stefan Salvatore', text: 'Damon is up to something.', timestamp: daysAgo(8, 19, 0), isMe: false, status: 'read' },
      { id: 'm8b', sender: 'Me', text: 'What did he do now?', timestamp: daysAgo(8, 19, 5), isMe: true, status: 'read' },
      { id: 'm8c', sender: 'Stefan Salvatore', text: 'He compelled the history teacher.', timestamp: daysAgo(8, 19, 10), isMe: false, status: 'read' },
      { id: 'm8d', sender: 'Me', text: 'Classic Damon ≡ƒÿæ', timestamp: daysAgo(8, 19, 15), isMe: true, status: 'read' },
      { id: 'm8e', sender: 'Stefan Salvatore', text: 'I have to protect Elena.', timestamp: daysAgo(5, 22, 10), isMe: false, status: 'read' },
    ],
  },
  {
    id: '9',
    name: 'Alaric Saltzman',
    avatar: 'https://ui-avatars.com/api/?name=Alaric+Saltzman&background=7f8c8d&color=fff',
    lastMessage: 'Class dismissed. ≡ƒôÜ',
    timestamp: daysAgo(6, 17, 0),
    unread: 0,
    messages: [
      { id: 'm9a', sender: 'Alaric Saltzman', text: 'Have you seen the new history books?', timestamp: daysAgo(9, 11, 0), isMe: false, status: 'read' },
      { id: 'm9b', sender: 'Me', text: 'Not yet, Ric.', timestamp: daysAgo(9, 11, 2), isMe: true, status: 'read' },
      { id: 'm9c', sender: 'Alaric Saltzman', text: 'They have a whole section on the supernatural. Curious, right?', timestamp: daysAgo(9, 11, 5), isMe: false, status: 'read' },
      { id: 'm9d', sender: 'Me', text: 'Muy curioso para ser un libro normal ≡ƒæÇ', timestamp: daysAgo(6, 17, 0), isMe: true, status: 'read' },
      { id: 'm9e', sender: 'Alaric Saltzman', text: 'Class dismissed. ≡ƒôÜ', timestamp: daysAgo(6, 17, 1), isMe: false, status: 'read' },
    ],
  },
  {
    id: '10',
    name: 'Luis Miguel',
    avatar: 'https://ui-avatars.com/api/?name=Luis+Miguel&background=f1c40f&color=222',
    lastMessage: 'No culpes a la noche... ≡ƒÄñ',
    timestamp: daysAgo(5, 0, 30),
    unread: 1,
    messages: [
      { id: 'm10a', sender: 'Luis Miguel', text: '┬┐Sera que no me amas?', timestamp: daysAgo(8, 21, 0), isMe: false, status: 'read' },
      { id: 'm10b', sender: 'Me', text: '┬íClaro que s├¡, Micky! ≡ƒî╣', timestamp: daysAgo(8, 21, 5), isMe: true, status: 'read' },
      { id: 'm10c', sender: 'Luis Miguel', text: 'La incondicional... esa canci├│n la hice pensando en alguien especial.', timestamp: daysAgo(7, 22, 0), isMe: false, status: 'read' },
      { id: 'm10d', sender: 'Me', text: '┬┐En qui├⌐n? ≡ƒæÇ', timestamp: daysAgo(7, 22, 3), isMe: true, status: 'read' },
      { id: 'm10e', sender: 'Luis Miguel', text: 'No culpes a la noche... ≡ƒÄñ', timestamp: daysAgo(5, 0, 30), isMe: false, status: 'read' },
    ],
  },
  {
    id: '11',
    name: 'Stevie Ray Vaughan',
    avatar: 'https://ui-avatars.com/api/?name=Stevie+Ray&background=2980b9&color=fff',
    lastMessage: 'Pride and Joy! ≡ƒÄ╡',
    timestamp: daysAgo(7, 19, 0),
    unread: 0,
    messages: [
      { id: 'm11a', sender: 'Stevie Ray Vaughan', text: 'Texas Flood is coming. ≡ƒîè', timestamp: daysAgo(12, 15, 0), isMe: false, status: 'read' },
      { id: 'm11b', sender: 'Me', text: 'Play Little Wing please! ≡ƒÄ╕', timestamp: daysAgo(12, 15, 5), isMe: true, status: 'read' },
      { id: 'm11c', sender: 'Stevie Ray Vaughan', text: 'Anything for a fan.', timestamp: daysAgo(10, 20, 0), isMe: false, status: 'read' },
      { id: 'm11d', sender: 'Me', text: '┬íSos el mejor!', timestamp: daysAgo(10, 20, 3), isMe: true, status: 'read' },
      { id: 'm11e', sender: 'Stevie Ray Vaughan', text: 'Pride and Joy! ≡ƒÄ╡', timestamp: daysAgo(7, 19, 0), isMe: false, status: 'read' },
    ],
  },
  {
    id: '12',
    name: 'James Brown',
    avatar: 'https://ui-avatars.com/api/?name=James+Brown&background=e74c3c&color=fff',
    lastMessage: 'I feel good! ≡ƒò║',
    timestamp: daysAgo(9, 18, 0),
    unread: 4,
    messages: [
      { id: 'm12a', sender: 'James Brown', text: 'Get up offa that thing! ≡ƒò║', timestamp: daysAgo(14, 20, 0), isMe: false, status: 'read' },
      { id: 'm12b', sender: 'Me', text: 'And dance until you feel better?', timestamp: daysAgo(14, 20, 5), isMe: true, status: 'read' },
      { id: 'm12c', sender: 'James Brown', text: 'You got it!', timestamp: daysAgo(12, 21, 0), isMe: false, status: 'read' },
      { id: 'm12d', sender: 'Me', text: 'Hardest working man in show business ≡ƒææ', timestamp: daysAgo(12, 21, 5), isMe: true, status: 'read' },
      { id: 'm12e', sender: 'James Brown', text: 'I feel good! ≡ƒò║', timestamp: daysAgo(9, 18, 0), isMe: false, status: 'read' },
    ],
  },
];
